### ISSUE TITLE
Theano and gpuarray/pygpu compatibility

### ISSUE THREAD

**Issue by mo-morikawa** [imatge-upc/activitynet-2016-cvprw#11]
Which versions of libgpuarray and pygpu should be used?  I get the following error with gpuarray 0.6.4

`RuntimeError: ('Wrong major API version for gpuarray:', 1, 'Make sure Theano and libgpuarray/pygpu are in sync.')`

**Comment by albertomontesg** [comment]
I don't remember the necessity to install `libgpuarray` or `pygpu` so I can not tell you which version did I used. But I think this is installed with Theano and the version I used is the one specified on the `requirements.txt` file: `Theano==0.8.2`
