### ISSUE TITLE
ActivitynetDataset python file is missing

### ISSUE THREAD

**Issue by muralidarant** [imatge-upc/activitynet-2016-cvprw#13]
I'm trying to run the 02 Exploring Dataset ipython notebook, but it failed with ImportError: No module named work.dataset.activitynet.

Where can I find the activitynet related python files?

Thanks,

**Comment by albertomontesg** [comment]
The notebooks folder is legacy code from the early stages of the project and some parts of the code are no longer available. The intention to keep is more illustrative than to run them.
