### ISSUE TITLE
model.pop_layer() in extract_features.py doesn't work

### ISSUE THREAD

**Issue by RyanCV** [imatge-upc/activitynet-2016-cvprw#17]
In the file extract_features.py, the keras version I used is 1.0.4, however, the function model.pop_layer() doesn't work, what should I do??

**Comment by albertomontesg** [comment]
This is because you have not install the correct version of Keras. It is a custom fork of Keras that is specified in the `requirements.txt` so to install all the dependencies you should run `pip3 install -r requirements.txt`
