### ISSUE TITLE
How to solve problem "No module named src.data "

### ISSUE THREAD

**Issue by 1461190388** [imatge-upc/activitynet-2016-cvprw#19]
Hello,  i tried a lot but unable to solve it , can any one help me please??

**Comment by jarpit96** [comment]
As an ugly fix, try moving your run_all_pipelines.py file one directory up.

**Comment by GauravKrRoy** [comment]
> Hello, i tried a lot but unable to solve it , can any one help me please??

@1461190388 Can u plese tell me how did you resolved it.
