### ISSUE TITLE
KeyError: load_weights fails because 'layer_names' is missing in extract_features.py

### ISSUE THREAD

**Issue by singhania1408** [imatge-upc/activitynet-2016-cvprw#21]
This error was coming on extract_features.py on line model.load_weights(). I am using tensorflow as backend, keras 2.0.1 and changed input dimension to 16, 112, 112, 3 of 1st layer group for working under tensorflow backend. Please help me out so that i can get correct h5 file for extracting features.

**Comment by 4rshdeep** [comment]
Same problem. Any Updates?

**Comment by singhania1408** [comment]
@4rshdeep I am confused how I can generate new weight file corresponding to sports dataset for 3d- CN. Do u have any knowledge regarding this??.. No one from admin side is replying?

**Comment by albertomontesg** [comment]
Check the Keras version using. In the `requirements.txt` file it is the version used which is a version modified of Keras 1.0.X. Also take into account that the code was tested and used using the Theano backend and with most recent versions may raise some incompatibilities.
