### ISSUE TITLE
What exactly is the dependencies for the project configuration?

### ISSUE THREAD

**Issue by qingtianwu** [imatge-upc/activitynet-2016-cvprw#27]
Can you tell which versions are the following dependencied: Ubuntu, python, cuda, cudnn, tensorflow, keras?

I've tried to switch keras from 1.0.4 to 2.0, CUDA from 10.1/10.1 to 8.0, cudnn is switching and tensorflow is reinstalled, still fail to run the pipeline.

My current configuration: Ubuntu 16.04, Anaconda 2.7.4 (python = 2.7.4), CUDA = 10.0, keras = 2.0. I have installed the dependencies followed by the "requirements.txt".

**Comment by MuhammadAsadJaved** [comment]
What is error?

**Comment by qingtianwu** [comment]
> What is error?
