### ISSUE TITLE
Environment details.

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [imatge-upc/activitynet-2016-cvprw#29]
Hi  am using Cuda 10 on ubuntu 16.04 and there is an error about Theano that 
Your cuDNN version is more recent than the one Theano officially supports. If you see any problems, try updating Theano or downgrading cuDNN to version 5.

Can you give the details of your environment and system? I
Ubuntu =
CUDA =
Cudnn =

etc?

**Comment by albertomontesg** [comment]
Hi, I can not recall the exact versions of the CUDA/cudnn software used to run this. I only remember I used a Titan X to do the training. Take into account that this code was developed 3 years ago, so the software used was the latest version at that time. I am aware that with the fast evolution of the Deep Learning frameworks, this code right now is barely runnable. My recommendation is to try to get the weights and architecture and rebuild the same computational graph with a more recent framework like TensorFlow. Sorry I can not help you more with this.
