### ISSUE TITLE
Error pop_layer() Model

### ISSUE THREAD

**Issue by jthoth** [imatge-upc/activitynet-2016-cvprw#3]
extracted_features.py

model.pop_layer()
AttributeError: 'Sequential' object has no attribute 'pop_layer'

Keras 1.1.1

**Comment by albertomontesg** [comment]
The version of Keras used is a fork with some modifications:
`pip install git+https://github.com/albertomontesg/keras.git@improved-3d-ops`
or install the `requirements.txt`
`pip install -r requirements.txt`
