### ISSUE TITLE
"Could not be read the video [video name]" when running "extract_features.p"

### ISSUE THREAD

**Issue by meegoStar** [imatge-upc/activitynet-2016-cvprw#6]
Hello, I'm running `extract_features.py` using the command `KERAS_BACKEND=theano python -u extract_features.py -d ~/Videos/videos`. Sometimes I see the program printing messages of `Could not be read the video [video name]`, for example `Could not be read the video Af_0zV79zsk`, while `Af_0zV79zsk.mp4` does exist under the path where I store all the downloaded videos of the ActivityNet dataset.

So my question is are those videos with this kind of messages printed still be extracted the C3D features?

**Comment by albertomontesg** [comment]
As you have downloaded `Af_0zV79zsk.mp4` video, it should still be there, but what shouldn't be is the `Af_0zV79zsk.npy` file at the extracted features directory.

At this [line](https://github.com/imatge-upc/activitynet-2016-cvprw/blob/master/scripts/extract_features.py#L102) it shows that when the video can not be read, it jumps to the next one without saving the extracted features.
