### ISSUE TITLE
[scripts] Potential bug in generate_output during create_stateful_dataset

### ISSUE THREAD

**Issue by escorciav** [imatge-upc/activitynet-2016-cvprw#8]
Hi guys,

Thank you for sharing your work. It is self-contained and easy to read.

The logic used in the function [generate_output](https://github.com/imatge-upc/activitynet-2016-cvprw/blob/b0bf5bb69fac4285013a6f63e24535bc960b1348/src/data.py#L33) is a little bit confusing to me. This [line](https://github.com/imatge-upc/activitynet-2016-cvprw/blob/b0bf5bb69fac4285013a6f63e24535bc960b1348/src/data.py#L60) appends the index of the label into `output` but the [else case](https://github.com/imatge-upc/activitynet-2016-cvprw/blob/b0bf5bb69fac4285013a6f63e24535bc960b1348/src/data.py#L61-L62) appends the label into `output`.
I noticed that the output might end up being something like `['none', 2, 2, 'none', 'none']`. This input generated an error with the function [to_categorical](https://github.com/imatge-upc/activitynet-2016-cvprw/blob/b0bf5bb69fac4285013a6f63e24535bc960b1348/src/data.py#L22).

Disclaimer: I haven't run the code from scratch. Feel free to close the issue, if you are sure about the logic of the if statement.

**Comment by albertomontesg** [comment]
Hi @escorciav,

You were right. It seems that writing a refactor of the code after the finish I change the function in a buggy way. It is already fixed it in this commit 32581d432fee500979241cc5ea69159403d66955. I have also shown a demonstration of the correct behavior in this [notebook](https://github.com/imatge-upc/activitynet-2016-cvprw/blob/master/notebooks/15%20Test%20Generation%20Output.ipynb).
